linebender/druid-widget-nursery

- examples/tree.rs
- src/lib.rs
- src/tree.rs
This is a simple implementation for a tree widget, with the associated example.
The content is the same as the PR proposed in druid ([\#1467](https://github.com/linebender/druid/pull/1467)).
This is my very first piece of rust code, so please bear with me, I might be doing things in a not-so-orthodox way. Also, I tried not to aim too high. I know the following limitations, which I'd like to lift in the future:
- hot/hovering does not seem to work correctly, though I assumed WidgetPod would handle it for me,
the node's labels are currently only "Label" widgets. It shall not be too hard to make it a generic type instead,
- animating the expand/collapse actions would be nice,
- the tree currently cannot be changed (nodes removed/added). That's maybe a harder task!
- very big trees: see …
> A tree widget

- examples/tree.rs
- src/tree.rs
The tree previously only displayed Label widgets. Now any widget can be used, not just label / text.
It is now possible to provide a closure which builds the widgets to the tree's constructor.
> The widget used for the tree node is now dynamic.

- examples/hot-reload/README.md
Pretty sure cagro run isn't a real command. Just sayin'
> Fix typo in a README

- examples/select.rs
- src/dropdown_select.rs
- src/lib.rs
- src/list_select.rs
- src/tree.rs
Adding two new widgets, a list selection widget, and a dropdown selection widget, [as shown in zulip post](https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/Dropdown.20Select/near/223815603).
> Dropdown Select Widget

- Cargo.toml
- examples/dropdown.rs
- examples/hot-reload/Cargo.toml
- examples/select.rs
- src/dropdown.rs
- src/dropdown_select.rs
- src/list_select.rs
Previously, if a dropdown window was smaller than its contents, the contents was not fully showed.
I added `new_sized` methods for `Dropdown` and `DropdownSelect` which specify a size of the dropdown windows, so that the windows can be scrolled when the contents is bigger than the windows.
> Make dropdown windows able to be sized

- examples/select.rs
- src/list_select.rs
This allows us to perform advanced actions (such as sending a
command) when a list item is selected.
Signed-off-by: Christopher N. Hesse <raymanfx@gmail.com>
> ListSelect: Add on_select action callback

- Cargo.toml
- examples/hot-reload/Cargo.toml
- examples/progress_bar.rs
- src/progress_bar.rs
Cleaned up default values config for ProgressBar, using KeyOrValue<T> instead of Option<T> to remove boilerplate code.
Thinking about using BackgroundBrush instead of piet::PaintBrush, but it messes up a lot of Trait derives.
> New progress bar

- src/animation/animated_value.rs
- src/animation/storage.rs
- Format animated_value.rs
- Remove redundant `.clone()`
- Disable clippy lint for animation storage (AS) type prefix
> Fix a few clippy errors

- src/lib.rs
- src/separator.rs
- Fix name by renaming from `seperator` to `separator`
- Group builder/non-builder methods together
- Rename `size` -> `width` for the line thickness, conforming to the
usual terminology for this
> Rename and clean-up separator

- examples/dropdown.rs
Follow-up to
https://github.com/linebender/druid-widget-nursery/pull/37
https://github.com/linebender/druid-widget-nursery/issues/31
---
Build will fail if not rebased on top of https://github.com/linebender/druid-widget-nursery/pull/42
> example/dropdown: submit DROP as a command instead of a notification

- .github/workflows/rust.yml
Currently, the hot_reload and future widgets are not scanned.
Ensure that CI scans code behind feature and target flags.
> ci/clippy: scan all targets and features

- src/dropdown_select.rs
Currently when clicking on the `dropdown_select` header a second time, it opens a new window.
It is expected that it collapses instead.
Collapse if open.
---
Build will fail if not rebased on top of https://github.com/linebender/druid-widget-nursery/pull/42
> select: collapse if open when clicked

- Cargo.toml
The async example uses a feature that is not declared, which causes
rust-analyzer to display an error.
> cargo/tokio: include time feature used by async example

- src/list_select.rs
This allows the selected ListItem to update before calling the on_select callback.
This is a partial solution to #57.  It works ok for regular clicks, however, if the user presses the mouse down in another section of the gui, drags over the list (that already has focus), and then releases the mouse a selection event is still triggered.  I'm not familiar enough with Druid to have a good idea on how to resolve that type of interaction.
> delay list selection until MouseUp

- README.md
- examples/titlebar.rs
- src/lib.rs
- src/titlebar.rs
Add a titlebar widget that can be used to replace the default titlebar and drag windows around or make a custom titlebar.
> Add titlebar widget

- README.md
This resolves the documentation issue that led to #20, and should help folks get started. I considered adding a disclaimer about it being an unstable development library, but the first paragraph communicates that, I think.
I used `[patch]` as suggested by @Maan2003 [on Zulip](https://xi.zulipchat.com/#narrow/stream/255910-druid-help/topic/.E2.9C.94.20DropdownSelect.20example.20broken.3F) - I knew nothing about `[patch]` before today, so please correct and edit as need be, but this seemed to do the trick!
> Add section on dependencies, with note on overriding druid version

- Cargo.toml
- examples/async.rs
- src/future_widget.rs
- src/lib.rs
JsFutures are not "Send", so it is not possible to send the future
to a worker task.
This patch spawns the future inside lifecycle() instead of sending
it to the AsyncDelegate. This also makes AsyncDelegate obsolete.
Signed-off-by: Dietmar Maurer <dietmar@proxmox.com>
> FutureWidget: make it work on target wasm32

- examples/flex-table.rs
- src/lib.rs
- src/table/flex_table.rs
- src/table/mod.rs
- src/table/table_column_width.rs
This is most useful to layout input forms. Provides similar fuctionality
as flutter Table class.
Uses a new module sub-directory ./src/table/, so that it is
possible to add other table implementation there (i.e. DataTable).
Signed-off-by: Dietmar Maurer <dietmar@proxmox.com>
> Add FlexTable widget

- src/dropdown.rs
TODO: Horizontal position is now correct, but the window has still
the wrong vertical position (off by about the size of the window
decorations).
Signed-off-by: Dietmar Maurer <dietmar@proxmox.com>
> dropdown: fix popup window position on linux/gtk

- Cargo.toml
- druid-widget-nursery-derive/Cargo.toml
- druid-widget-nursery-derive/src/lib.rs
- druid-widget-nursery-derive/src/prism.rs
- examples/prisms.rs
- src/prism.rs
- tests/prism.rs
> Add a derive macro for Prism

- Cargo.toml
- examples/material_icons.rs
- src/lib.rs
- src/material_icons.rs
This PR adds a new widget that displays an icon from the [material icons set](https://fonts.google.com/icons). Color is inherited from text color and can optionally be customized. Size defaults to the "given" icon size, but can be changed using constraints. It will prioritize preserving aspect ratio over minimizing difference from the default icon size (I've added an example to demonstrate how to change icons using constraints).
Currently only the normal (my word) icon variants are available. There are also other variants (e.g. two-tone) but I did not include them because the crate size & build time gets quite large. If there is demand I will add them, possibly behind features.
> Add material icons

- Cargo.toml
- examples/animated_value.rs
- examples/animation-curves.rs
- examples/animator.rs
- src/animation/curve.rs
- src/animation/mod.rs
- src/multi_value.rs
I think it is a good idea to remove the nested `AnimationCurve`subtypes `SimpleCurve` and `CustomCurve`. We can do everything without them.
I will add more documentation if this is considered for a merge ...
> Cleanup animation curve

- Cargo.toml
- src/dropdown.rs
This finally fixes the dropdown position on gtk/linux. This needs latest druid with:
https://github.com/linebender/druid/pull/2117
> Consider content insets

- Cargo.toml
- examples/json_viewer.rs
- examples/material_icons.rs
- src/animation/mod.rs
- src/dropdown.rs
- src/mask.rs
- src/on_change.rs
- src/on_cmd.rs
- src/table/mod.rs
- src/theme_loader/mod.rs
This fixes building the examples. The problem comes from how `clap` has superseded `structopt` for derived argument parsing.
Closes #118
> Fix issue building with qu.

- examples/stack_tooltip.rs
- src/stack_tooltip.rs
- src/widget_ext.rs
No longer requires outer wrapper widget.
Fewer command round trips.
Correctly handle reaching window edges.
Uses fewer unnecessary widget extensions (we implement Widget already
so there was no point).
Includes a cancellation widget extension, which will prevent a parent
tooltip displaying over the child.
Significantly expanded demo to cover edge cases and fully showcase new
features.
> Improve stack based tooltips

- examples/stack_tooltip.rs
- src/stack_tooltip.rs
- src/widget_ext.rs
Round 3 of Stack based Tooltips
The biggest things here is that it utilises z-index painting to ensure that tooltips always render over surrounding widgets.
Also adds a wealth of customization options, allowing you to set modify the appearance of the tooltip text as flexibly as you would the RichText widget (the API is only slightly rougher than the regular Label - if you've used RichText it's almost exactly the same), You can also set the background colour, border width and border color.
> Stack based tooltips v3
