linebender/druid-widget-nursery

- Cargo.toml
- examples/canvas.rs
- src/canvas.rs
- src/lib.rs
I've talked for a while about a canvas for layout - here's my approach to it.
I also ran into the world of lensing to work with numbers in a textbox. The lens I knocked together works as I desired, but I think it's pretty gnarly. I'm interested in comments on it (or revisions!) but I don't endorse it's use elsewhere 🤣
> Create a canvas widget, and accompanying example

- Cargo.toml
- examples/dropdown.rs
- src/dropdown.rs
- src/lib.rs
> Dropdown changes

- examples/select.rs
- src/dropdown_select.rs
- src/list_select.rs
- src/tree.rs
And split ListSelect into the build_widget function and the controller, following Robert's comment.
> Fix Clippy warnings

- README.md
- examples/multi_value.rs
- examples/partial.rs
- src/lib.rs
- src/multi_value.rs
- src/partial.rs
The three Widgets work as desired, except i did not found a way to disable a widget to ensure that it cannot gain Focus until it is enabled again
> Implement MultiRadio, MultiCheckbox and PartialWidget

- examples/async.rs
- examples/multi_value.rs
- examples/partial.rs
- src/animation/state.rs
- src/multi_value.rs
- src/partial.rs
Note that the partial example does compile because of `PartialWidget::with_closures` being missing.
> Fix examples

- Cargo.toml
- examples/navigator.rs
- src/navigator.rs
https://github.com/linebender/druid-widget-nursery/issues/15
> making some updates to navigator widget and adding example

- Cargo.toml
- README.md
- examples/progress_bar.rs
- src/lib.rs
- src/progress_bar.rs
A more configurable version of the ProgressBar widget. Also added dependency 'tracing'
> New progress bar

- src/computed.rs
- src/lib.rs
Widget to dynamically compute data. It is like Label::dynamic but more general
> ComputedWidget

- README.md
- examples/animated_value.rs
- src/animation/animated_value.rs
- src/animation/mod.rs
Adding a helper struct to create simple transitions.
> AnimatedValue

- examples/animated_value.rs
- examples/dropdown.rs
- examples/partial.rs
- examples/progress_bar.rs
Fix the build by commenting out part of the `partial.rs` test. Searching
through the git history did not yield any relevant result on how to fix
this, so hopefully the author can fix it in a later change.
Also clean-up a bit some build warnings.
> Fix build by commenting broken test

- Cargo.toml
- src/dropdown.rs
- src/dropdown_select.rs
- workspace.code-workspace
> Fixes for dropdown-select button not showing a subwindow when pressed

- examples/animator.rs
- examples/hot-reload/Cargo.toml
- examples/hot-reload/src/lib.rs
- examples/multi_value.rs
- examples/partial.rs
- src/hot_reload/mod.rs
- src/lib.rs
- src/multi_value.rs
- src/partial.rs
- src/progress_bar.rs
Fix or silence most clippy lints
> Fix more clippy lints

- .gitignore
- Cargo.toml
- workspace.code-workspace
Make the example inspectable by rust-analyzer.
> hot-reload example in workspace

- Cargo.toml
- README.md
- examples/todo_list.rs
- src/future_widget.rs
- src/lib.rs
- src/list_filter.rs
Adds a widget which filters a list for its inner widget.
> Filter list

- Cargo.toml
- README.md
- examples/splits.rs
- src/lib.rs
- src/splits.rs
My attempt on a multiple resizable splits, use like a List.
> Splits: Multiple resizable splits

- src/lib.rs
- src/macros.rs
These create unique selectors and keys. Also, We should have a convention for selectors.
> selectors and keys macros

- examples/tree.rs
- src/lib.rs
- src/tree.rs
The relevant example was updated to showcase the feature.
Closes #56
> [Tree] reflect changes in the data

- src/context_traits.rs
- src/lib.rs
This is work of @rjwittams
See linebender/druid#1611 for description. 
Moving this to nursery lets us experiment and find situations where these will be useful
> Add context traits

- src/context_traits.rs
it is no longer available in druid. and cause infinite recursion if
called
> Remove RequestCtx::set_menu

- src/macros.rs
sorry missed this in match_command pr
> remove panic from match_command doc test

- src/wedge.rs
Even if the basic widget height has been changed.
> Vertically centre the wedge

- Cargo.toml
- examples/json_viewer.rs
This PR adds an example JSON viewer.
I added it because it is surprisingly hard to find a good one, and also because it shows off the tree widget neatly.
> Add json viewer example

- src/autofocus.rs
AutoFocus doesn't work when widgets are created upon window connection, but only shown at a later point.
In my case, this happened with an enum `AppState` (using [druid-enums](https://github.com/luleyleo/druid-enums)) switching to one of the other cases.
After asking on Zulip, @Maan2003 proposed a solution. It works, so here's a PR. 🙂
> AutoFocus runs when a widget is added (instead of window connection)

- Cargo.toml
- examples/advanced_slider_demo.rs
- examples/dropdown.rs
- examples/titlebar.rs
- src/advanced_slider.rs
- src/context_traits.rs
- src/dropdown_select.rs
- src/future_widget.rs
- src/lib.rs
- src/progress_bar.rs
- src/titlebar.rs
- src/tooltip.rs
- src/widget_ext.rs
The only real changes are in the second commit, 
went through the examples and everything seemed the same afaict.
I wasn't sure the rules on rustfmt, happy to do away with that commit if it would cause anybody conflicts or otherwise unwanted.
> Update to main

- README.md
use a git patch, not a crates-io patch
> [patch] druid properly

- examples/animated_value.rs
- examples/animation-curves.rs
- src/animation/animated_value.rs
- src/animation/controller.rs
- src/animation/interpolate.rs
- src/animation/mod.rs
- src/multi_value.rs
Factor out animation controller functionality.
> Animation controller

- examples/mask.rs
- src/lib.rs
- src/mask.rs
We use this all the time with other frameworks to give feedback to the user while loading data from the server.
> new Mask widget
